#!/bin/bash

USERID=$(id -u) # Get the user ID of the current user. This is used to check if the script is being run with root privileges.
R="\e[31m"  # Define a variable R that contains the ANSI escape code for red color. This will be used to print error messages in red.
G="\e[32m" # Define a variable G that contains the ANSI escape code for green color. This will be used to print success messages in green.
Y="\e[33m"  # Define a variable Y that contains the ANSI escape code for yellow color. This will be used to print warning messages in yellow.
LOGS_FOLDER="/var/log/shellscripting-logs" # Define a variable LOGS_FOLDER that contains the path to the folder where log files will be stored. This is used to organize logs generated by the script.
LOG_FILE=$(echo $0 | cut -d "." -f 1)  # Define a variable LOG_FILE that contains the name of the log file. It is derived from the script's name by removing the extension. This helps in identifying logs for different scripts.
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S") # Define a variable TIMESTAMP that contains the current date and time in a specific format. This is used to create unique log file names and to record when the script was executed.
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log" # Define a variable LOG_FILE_NAME that combines the LOGS_FOLDER, LOG_FILE, and TIMESTAMP to create a unique log file name for each execution of the script. This ensures that logs are organized and easily identifiable.

VALIDATE(){  # Define a function named VALIDATE that takes two arguments: the first is the exit status of a command, and the second is a message describing the action being validated. This function will be used to check if a command executed successfully and to print appropriate messages.
    if [ $1 -ne 0 ]  # Check if the first argument (exit status) is not equal to 0, which indicates a failure.
    then 
        echo -e "$2 ... $R FAILURE"
        exit 1
    else
        echo -e "$2 ... $G SUCCESS"
    fi
}

echo "Script execution started at $TIMESTAMP" &>>$LOG_FILE_NAME

if [ $USERID -ne 0 ]
then
    echo "ERROR:: You must have sudo access to execute this script"
    exit 1 #other than 0
fi

for package in $@
do
    dnf list installed $package &>>$LOG_FILE_NAME

    if [ $? -ne 0 ]
    then # not installed
        dnf install $package -y &>>$LOG_FILE_NAME
        VALIDATE $? "Installing $package"
    else
        echo -e "$package is already ... $Y INSTALLED"
    fi
done